spring.application.name=assigment-hub

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.port=8080

spring.threads.virtual.enabled=true

logging.level.root=WARN
spring.datasource.hikari.maximum-pool-size=150
spring.datasource.hikari.connection-timeout=1500
spring.datasource.hikari.idle-timeout=30000

spring.jpa.open-in-view=false